language: cpp
dist: trusty
sudo: required
os:
  - linux
before_install:
  - pushd ..
  - wget https://downloads.arduino.cc/arduino-1.8.3-linux64.tar.xz
  - tar xf arduino-1.8.3-linux64.tar.xz
  - popd
install:
  - sh -c '. ./.kaleidoscope-builder.conf && setup'
script:
  - make build ARDUINO_PATH=$(pwd)/../arduino-1.8.3 SKETCHBOOK_DIR=$(pwd)
